version: '3.7'

services:
  frontend:
    image: frontend-app
    build:
      context: .
    ports: [ '5173:5173' ]
    restart: always
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: